export const AppConstClass = {

    OFFLINE_MESSAGE: "Your device is not connected to Internet. Please check your connection and try again.",
    ERROR_MESSAGE : "issue",
    HELP_DESK_MAIL : "mail@myshoppe.live", 
    heldesk_number :"9937027999",
    invite : "Invite Friends",
    shareMessage_Android : "Hey, MyShoppeLive is a fast,simple and secure app. Download it on https://play.google.com/store/apps/details?id=com.epistemetek.myshoppecustomer",
    shareMessage_ios : "Hey, MyShoppeLive is a fast,simple and secure app. Download it on Upcoming Ios link",
    AppHeader : "MYSHOPPE.LIVE",
    TandC : "TERMS & CONDITIONS",
    help : "HELP",
    PP : "PRIVACY POLICY",
    share : "SHARE",
    goShop : "GO SHOPPING",
    Gallery : "GALLERY",

    offers : "OFFERS",
    signup : "SIGNUP",
    newProduct : "NEW PRODUCTS",
    login : "LOGIN",
    exStore : "EXCLUSIVE STORES",
    account : "MY ACCOUNT",
    spStore : "SPECALITY STORES",
    cart : "MY CART",
    wishlist : "WISHLIST",
    orders : "MY ORDERS",
    logout : "LOGOUT",
};