

export const SAVE_FEEDBACK_DETAILS_ONE = "SAVE_FEEDBACK_DETAILS_ONE";
export const SAVE_FEEDBACK_DETAILS_TWO = "SAVE_FEEDBACK_DETAILS_TWO";
export const SAVE_FEEDBACK_DETAILS_THREE = "SAVE_FEEDBACK_DETAILS_THREE";
export const SAVE_FEEDBACK_DETAILS_FOUR = "SAVE_FEEDBACK_DETAILS_FOUR";
export const SAVE_FEEDBACK_DETAILS_SUBMITTED = "SAVE_FEEDBACK_DETAILS_SUBMITTED";

// profile reducer
export const SAVE_PROFILE_DETAILS = "SAVE_PROFILE_DETAILS";